name: "build and push to docker hub"
on: 
  push: 
    main

jobs:
  build_push:
    name: "build push to docker"
    runs-on: ubuntu-latest
    step:
      - uses: actions/checkout@v2
      - name: "Build Docker"
        run: docker build -t fgdevs/kelaskita:1.0.0 .

      - name: "Login Registry Docker Hub"
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_TOKEN }} 
      
      - name: "Push to Docker Hub"
        run: docker push fgdevs/kelaskita:1.0.0
